package kirillale.lakinais.bot.master

object MasterCallbackData {
    const val PREFIX = "m:"
    const val MENU = "m:menu"
    const val OPEN_MENU = "m:open"
    const val OPEN_CONFIRM = "m:open:cfm"
    const val OPEN_MINUS = "m:open:-"
    const val OPEN_PLUS = "m:open:+"
    const val OPEN_PRESET_PREFIX = "m:open:p:"
    const val OPEN_CFG_WEEKDAY = "m:open:wd"
    const val OPEN_CFG_WEEKEND = "m:open:we"
    const val BOOKS_TODAY = "m:btoday"
    const val BOOKS_UPCOMING = "m:bup"
    const val BOOKS_PICK_DAY = "m:bpick"
    const val BOOKS_DAY_PREFIX = "m:bday:"
    const val BOOK_PREFIX = "m:book:"
    const val BOOK_CANCEL_PREFIX = "m:bcxl:"
    const val BOOK_CONFIRM_PREFIX = "m:bcfm:"
    const val CLOSE_PICK = "m:close"
    const val CLOSE_DAY_PREFIX = "m:cls:"
    const val CLIENT_MODE = "m:client"
    const val BLOCK_TIME = "m:block"
    const val EDIT_DAY_PICK = "m:eday"
    const val EDIT_DAY_PREFIX = "m:eday:"

    const val SCH_FIELD_PREFIX = "m:sch:f:"
    const val SCH_BREAK_TOGGLE = "m:sch:brk"
    const val SCH_TIME_PREFIX = "m:sch:t:"
    const val SCH_SAVE_DAY = "m:sch:save"
    const val SCH_APPLY_WEEKENDS = "m:sch:apply:we"
    const val SCH_APPLY_WEEKDAYS = "m:sch:apply:wd"
    const val SCH_BACK_OPEN = "m:sch:back:open"
    const val SCH_BACK_PROFILE = "m:sch:back:prof"

    const val BLOCK_PICK_DAY_PREFIX = "m:block:day:"
    const val BLOCK_PICK_START_PREFIX = "m:block:st:"
    const val BLOCK_PICK_END_PREFIX = "m:block:end:"
    const val BLOCK_CONFIRM = "m:block:cfm"
    const val BLOCK_DELETE_PREFIX = "m:block:del:"
    const val BLOCK_BACK_TO_DAYS = "m:block:back"
}
